/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tracnghiemapplication.UI;

/**
 *
 * @author SON
 */
public class PanelCauHoiTuLuan extends javax.swing.JPanel {

    /**
     * Creates new form UICauHoiTuLuan
     */
    public PanelCauHoiTuLuan() {
        initComponents();
    }
    
    public void setInit(int cauSo, String cauHoi) {
        jLBCau.setText("Câu " + String.valueOf(cauSo));
        jTACauHoi.setText(cauHoi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBCau = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTACauHoi = new javax.swing.JTextArea();
        jTFCauTraLoi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLBCau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLBCau.setText("Câu 1 :");

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTACauHoi.setEditable(false);
        jTACauHoi.setColumns(20);
        jTACauHoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTACauHoi.setLineWrap(true);
        jTACauHoi.setRows(5);
        jTACauHoi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTACauHoi);

        jTFCauTraLoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Trả Lời");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jTFCauTraLoi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBCau)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLBCau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTFCauTraLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBCau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTACauHoi;
    public javax.swing.JTextField jTFCauTraLoi;
    // End of variables declaration//GEN-END:variables
}
