/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tracnghiemapplication.UI;

/**
 *
 * @author SON
 */
public class PanelKetQua extends javax.swing.JPanel {

    /**
     * Creates new form PanelKetQua
     */
    public PanelKetQua() {
        initComponents();
    }
    
    public void setInit(String tieuDe, String namHoc, String kyHoc, String thoiGian, double diemDatDuoc, int soCauSai, int soCauDung, String tenDe) {
        jLBTieuDe.setText(tieuDe.toUpperCase());
        jLBNamHoc.setText(namHoc);
        jLBKy.setText(kyHoc);
        jLBThoiGian.setText(String.valueOf(thoiGian) + " phút");
        jLBDiem.setText(String.valueOf(diemDatDuoc) + " điểm");
        jLBCauSai.setText(String.valueOf(soCauSai) + " câu");
        jLBCauDung.setText(String.valueOf(soCauDung) + " câu");
        jLBTenDe.setText(tenDe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLBTieuDe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLB = new javax.swing.JLabel();
        jLBTG = new javax.swing.JLabel();
        jLBNamHoc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLBDiem = new javax.swing.JLabel();
        jLBThoiGian = new javax.swing.JLabel();
        jLBKy = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLBCauSai = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLBCauDung = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLBTenDe = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Đề Thi : ");

        jLBTieuDe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBTieuDe.setText("BÀI THI MÔN LẬP TRÌNH HƯỚNG ĐỐI TƯỢNG");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Năm Học :");

        jLB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLB.setText("Kỳ :");

        jLBTG.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBTG.setText("Thời Gian :");

        jLBNamHoc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBNamHoc.setText("2016-2017");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Điểm Đạt Được :");

        jLBDiem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBDiem.setText("10 điểm");

        jLBThoiGian.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBThoiGian.setText("10 phút");

        jLBKy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBKy.setText("kỳ I");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Số Câu Sai :");

        jLBCauSai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBCauSai.setText("3 câu");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Số Câu Đúng :");

        jLBCauDung.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBCauDung.setText("2 câu");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Tên Đề :");

        jLBTenDe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLBTenDe.setText("LTHDTKyI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLBTG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBTenDe)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLBNamHoc)
                                .addComponent(jLBThoiGian)
                                .addComponent(jLBDiem))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLB, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7))
                            .addGap(3, 3, 3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLBCauDung)
                                .addComponent(jLBKy)
                                .addComponent(jLBCauSai)))
                        .addComponent(jLBTieuDe)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLBTieuDe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLB)
                    .addComponent(jLBNamHoc)
                    .addComponent(jLBKy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBTG)
                    .addComponent(jLBThoiGian)
                    .addComponent(jLabel5)
                    .addComponent(jLBCauSai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLBDiem)
                    .addComponent(jLabel7)
                    .addComponent(jLBCauDung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLBTenDe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLB;
    private javax.swing.JLabel jLBCauDung;
    private javax.swing.JLabel jLBCauSai;
    private javax.swing.JLabel jLBDiem;
    private javax.swing.JLabel jLBKy;
    private javax.swing.JLabel jLBNamHoc;
    private javax.swing.JLabel jLBTG;
    private javax.swing.JLabel jLBTenDe;
    private javax.swing.JLabel jLBThoiGian;
    private javax.swing.JLabel jLBTieuDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
