/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tracnghiemapplication.UI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import tracnghiemapplication.ClassesHandle.MonHoc;

/**
 *
 * @author SON
 */
public class UIChucNang extends javax.swing.JFrame {
    /**
     * Creates new form UIChucNang
     */
    public UIChucNang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSoanCauHoi = new javax.swing.JButton();
        btnDanhGia = new javax.swing.JButton();
        btnXayDungDe = new javax.swing.JButton();
        btnLamBaiThi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSoanCauHoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSoanCauHoi.setText("Soạn Câu Hỏi");
        btnSoanCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoanCauHoiActionPerformed(evt);
            }
        });

        btnDanhGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDanhGia.setText("Đánh Giá Kết Quả");
        btnDanhGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhGiaActionPerformed(evt);
            }
        });

        btnXayDungDe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXayDungDe.setText("Xây Dựng Đề Thi");
        btnXayDungDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXayDungDeActionPerformed(evt);
            }
        });

        btnLamBaiThi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLamBaiThi.setText("Làm Bài Thi");
        btnLamBaiThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamBaiThiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnSoanCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnXayDungDe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnLamBaiThi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(btnDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSoanCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXayDungDe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamBaiThi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoanCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoanCauHoiActionPerformed
        // TODO add your handling code here:
        UIChonMonHoc chonMonHoc = new UIChonMonHoc();
        chonMonHoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        chonMonHoc.setVisible(true);
        chonMonHoc.getButton().addActionListener((ActionEvent e) -> {
            chonMonHoc.dispose();
            String monHoc = String.valueOf(chonMonHoc.getComboBox().getSelectedItem());
            MonHoc tmpMonHoc = null;
            for(Object obj : chonMonHoc.getAlMonHoc()) {
                if(((MonHoc)obj).getTenMonHoc().equals(monHoc)) {
                    tmpMonHoc = (MonHoc)obj;
                    break;
                }
            }
            UISoanCauHoi soanCauHoi = new UISoanCauHoi();
            soanCauHoi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            soanCauHoi.setMonHoc(tmpMonHoc);
            soanCauHoi.setVisible(true);
        });
    }//GEN-LAST:event_btnSoanCauHoiActionPerformed

    private void btnXayDungDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXayDungDeActionPerformed
        // TODO add your handling code here:
        UIChonMonHoc chonMonHoc = new UIChonMonHoc();
        chonMonHoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        chonMonHoc.setVisible(true);
        chonMonHoc.getButton().addActionListener((ActionEvent e) -> {
            chonMonHoc.dispose();
            String monHoc = String.valueOf(chonMonHoc.getComboBox().getSelectedItem());
            MonHoc tmpMonHoc = null;
            for(Object obj : chonMonHoc.getAlMonHoc()) {
                if(((MonHoc)obj).getTenMonHoc().equals(monHoc)) {
                    tmpMonHoc = (MonHoc)obj;
                    break;
                }
            }
            UIQuanLyDeThi quanLyDeThi = new UIQuanLyDeThi();
            quanLyDeThi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            quanLyDeThi.setMonHoc(tmpMonHoc);
            quanLyDeThi.setVisible(true);
        });
    }//GEN-LAST:event_btnXayDungDeActionPerformed

    private void btnLamBaiThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamBaiThiActionPerformed
        // TODO add your handling code here:
        UIChonMonHoc chonMonHoc = new UIChonMonHoc();
        chonMonHoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        chonMonHoc.setVisible(true);
        chonMonHoc.getButton().addActionListener((ActionEvent e) -> {
            chonMonHoc.dispose();
            String monHoc = String.valueOf(chonMonHoc.getComboBox().getSelectedItem());
            MonHoc tmpMonHoc = null;
            for(Object obj : chonMonHoc.getAlMonHoc()) {
                if(((MonHoc)obj).getTenMonHoc().equals(monHoc)) {
                    tmpMonHoc = (MonHoc)obj;
                    break;
                }
            }
            UILamBai lamBaiThi = new UILamBai();
            lamBaiThi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            lamBaiThi.setMonHoc(tmpMonHoc);
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            lamBaiThi.setMaximumSize(d);
            lamBaiThi.setExtendedState(JFrame.MAXIMIZED_BOTH);
            lamBaiThi.setVisible(true);
        });
    }//GEN-LAST:event_btnLamBaiThiActionPerformed

    private void btnDanhGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhGiaActionPerformed
        // TODO add your handling code here:
        UIChonMonHoc chonMonHoc = new UIChonMonHoc();
        chonMonHoc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        chonMonHoc.setVisible(true);
        chonMonHoc.getButton().addActionListener((ActionEvent e) -> {
            chonMonHoc.dispose();
            String monHoc = String.valueOf(chonMonHoc.getComboBox().getSelectedItem());
            MonHoc tmpMonHoc = null;
            for(Object obj : chonMonHoc.getAlMonHoc()) {
                if(((MonHoc)obj).getTenMonHoc().equals(monHoc)) {
                    tmpMonHoc = (MonHoc)obj;
                    break;
                }
            }
            UIDanhGiaKetQua danhGiaKetQua = new UIDanhGiaKetQua();
            danhGiaKetQua.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            danhGiaKetQua.setMonHoc(tmpMonHoc);
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            danhGiaKetQua.setMaximumSize(d);
            danhGiaKetQua.setExtendedState(JFrame.MAXIMIZED_BOTH);
            danhGiaKetQua.setVisible(true);
        });
    }//GEN-LAST:event_btnDanhGiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UIChucNang().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhGia;
    private javax.swing.JButton btnLamBaiThi;
    private javax.swing.JButton btnSoanCauHoi;
    private javax.swing.JButton btnXayDungDe;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
