/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tracnghiemapplication.UI;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.Timer;
import tracnghiemapplication.ClassesHandle.CauHoi;
import tracnghiemapplication.ClassesHandle.DeThi;
import tracnghiemapplication.ClassesHandle.FileObject;
import tracnghiemapplication.ClassesHandle.MonHoc;

/**
 *
 * @author SON
 */
public class UILamBai extends javax.swing.JFrame {
    private MonHoc monHoc;
    private DeThi deThi;
    Timer t;
    private long count;
    /**
     * Creates new form UILamBai
     */
    public UILamBai() {
        initComponents();
    }
    
    public void setMonHoc(MonHoc monHoc) {
        this.monHoc = monHoc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTieuDe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLBTenDeThi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLBTenMonHoc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLBNamHoc = new javax.swing.JLabel();
        jLBThoiGian = new javax.swing.JLabel();
        jLBKyHoc = new javax.swing.JLabel();
        jLCounterTime = new javax.swing.JLabel();
        btnBatDau = new javax.swing.JButton();
        btnNopBaiThi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelNoiDung = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên Đề Thi :");

        jLBTenDeThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBTenDeThi.setText("BÀI THI MÔN LẬP TRÌNH HƯỚNG ĐỐI TƯỢNG");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bộ Môn : ");

        jLBTenMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBTenMonHoc.setText("Lập Trình Hướng Đối Tượng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Năm Học :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kỳ Học :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Thời Gian :");

        jLBNamHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBNamHoc.setText("2016-2017");

        jLBThoiGian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBThoiGian.setText("10 phút");

        jLBKyHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBKyHoc.setText("Kỳ 1");

        jLCounterTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnBatDau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBatDau.setText("Bắt Đầu");
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });

        btnNopBaiThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNopBaiThi.setText("Nộp Bài Thi");
        btnNopBaiThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopBaiThiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Thời Gian Làm Bài :");

        javax.swing.GroupLayout jPanelTieuDeLayout = new javax.swing.GroupLayout(jPanelTieuDe);
        jPanelTieuDe.setLayout(jPanelTieuDeLayout);
        jPanelTieuDeLayout.setHorizontalGroup(
            jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                .addGroup(jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                        .addComponent(jLBTenMonHoc)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel7))
                    .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                        .addComponent(jLBTenDeThi)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBNamHoc)
                    .addComponent(jLBThoiGian))
                .addGap(108, 108, 108)
                .addGroup(jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLBKyHoc))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCounterTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatDau)
                    .addComponent(btnNopBaiThi))
                .addContainerGap())
        );

        jPanelTieuDeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatDau, btnNopBaiThi});

        jPanelTieuDeLayout.setVerticalGroup(
            jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBTenDeThi)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLBNamHoc)
                    .addComponent(jLBKyHoc)
                    .addComponent(btnBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLBTenMonHoc)
                    .addComponent(jLabel7)
                    .addComponent(jLBThoiGian)
                    .addComponent(jLCounterTime)
                    .addComponent(btnNopBaiThi)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTieuDeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatDau, btnNopBaiThi});

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout jPanelNoiDungLayout = new javax.swing.GroupLayout(jPanelNoiDung);
        jPanelNoiDung.setLayout(jPanelNoiDungLayout);
        jPanelNoiDungLayout.setHorizontalGroup(
            jPanelNoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        jPanelNoiDungLayout.setVerticalGroup(
            jPanelNoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelNoiDung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //Phan tieu de
        Random rd = new Random();
        int soDeThi = rd.nextInt(monHoc.getDeThi().size()) + 0;
        deThi = monHoc.getDeThi().get(soDeThi);
        count = Integer.parseInt(deThi.getThoiGian()) * 60;
        /*
        jLBTenDeThi.setText("BÀI THI MÔN " + monHoc.getTenMonHoc().toUpperCase());
        jLBTenMonHoc.setText(monHoc.getTenMonHoc());
        jLBNamHoc.setText(deThi.getNamHoc());
        jLBThoiGian.setText(deThi.getThoiGian() + " phút");
        jLBKyHoc.setText("Kỳ " + deThi.getLoaiDeThi());
        
        //Phan noi dung
        jPanelNoiDung.setLayout(new BoxLayout(jPanelNoiDung, BoxLayout.Y_AXIS));
        
        for(CauHoi cauHoi : deThi.getDSCauHoi()) {
            JPanel tmpPanel = cauHoi.inCauHoi(deThi.getDSCauHoi().indexOf(cauHoi) + 1);
            jPanelNoiDung.add(tmpPanel);
            jPanelNoiDung.validate();
            jPanelNoiDung.repaint();
        }
        */
    }//GEN-LAST:event_formWindowOpened

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        // TODO add your handling code here:
        jLBTenDeThi.setText("BÀI THI MÔN " + monHoc.getTenMonHoc().toUpperCase());
        jLBTenMonHoc.setText(monHoc.getTenMonHoc());
        jLBNamHoc.setText(deThi.getNamHoc());
        jLBThoiGian.setText(deThi.getThoiGian() + " phút");
        jLBKyHoc.setText(deThi.getLoaiDeThi());
        
        //Phan noi dung
        jPanelNoiDung.setLayout(new BoxLayout(jPanelNoiDung, BoxLayout.Y_AXIS));
        
        for(CauHoi cauHoi : deThi.getDSCauHoi()) {
            JPanel tmpPanel = cauHoi.inCauHoi(deThi.getDSCauHoi().indexOf(cauHoi) + 1);
            jPanelNoiDung.add(tmpPanel);
            jPanelNoiDung.validate();
            jPanelNoiDung.repaint();
        }
        
        btnBatDau.setEnabled(false);
        t = new Timer(1000, (e) -> {
            if(count == 0) {
                jLCounterTime.setText("Hết giờ");
                btnNopBaiThiActionPerformed(evt);
                t.stop();
            }
            int hours = (int) count / 3600;
            int remainder = (int) count - hours * 3600;
            int mins = remainder / 60;
            remainder = remainder - mins * 60;
            int secs = remainder;
            jLCounterTime.setText((hours < 10? "0" + String.valueOf(hours) : String.valueOf(hours)) + ":" + (mins < 10? "0" + String.valueOf(mins) : String.valueOf(mins)) + ":" + (secs < 10? "0" + String.valueOf(secs) : String.valueOf(secs)));
            count--;
        });
        t.start();
    }//GEN-LAST:event_btnBatDauActionPerformed

    private void btnNopBaiThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopBaiThiActionPerformed
        // TODO add your handling code here:
        t.stop();
        btnNopBaiThi.setEnabled(false);
        double tongDiem = 0;
        //Component[] cauHoiTrongDe = jPanelNoiDung.getComponents();
        List component = Arrays.asList(jPanelNoiDung.getComponents());
        for(Object comp : component) {
            if(comp instanceof PanelCauHoiTracNghiem) {
                ArrayList<JRadioButton> dsRadioButton = ((PanelCauHoiTracNghiem) comp).dsRadioButton;
                ArrayList<String> anwsers = new ArrayList<>();
                for(JRadioButton jrb : dsRadioButton) {
                    if(jrb.isSelected()) {
                        anwsers.add(jrb.getText());
                    }
                }
                CauHoi cauHoi = deThi.getDSCauHoi().get(component.indexOf(comp));
                tongDiem += cauHoi.tinhDiem(anwsers);
            }
            if(comp instanceof PanelCauHoiTuLuan) {
                ArrayList<String> anwsers = new ArrayList<>();
                anwsers.add(((PanelCauHoiTuLuan) comp).jTFCauTraLoi.getText().toUpperCase());
                CauHoi cauHoi = deThi.getDSCauHoi().get(component.indexOf(comp));
                tongDiem += cauHoi.tinhDiem(anwsers);
            }
        }
        System.out.println(tongDiem);
        if(tongDiem > deThi.getDiemThi()) {
            FileObject fileObject = new FileObject();
            deThi.setDiemThi(tongDiem);
            fileObject.updateObjectInFile("MonHoc.txt", monHoc);
        }
    }//GEN-LAST:event_btnNopBaiThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UILamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UILamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UILamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UILamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UILamBai().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.JButton btnNopBaiThi;
    private javax.swing.JLabel jLBKyHoc;
    private javax.swing.JLabel jLBNamHoc;
    private javax.swing.JLabel jLBTenDeThi;
    private javax.swing.JLabel jLBTenMonHoc;
    private javax.swing.JLabel jLBThoiGian;
    private javax.swing.JLabel jLCounterTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelNoiDung;
    private javax.swing.JPanel jPanelTieuDe;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
