/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tracnghiemapplication.UI;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import tracnghiemapplication.ClassesHandle.FileObject;
import tracnghiemapplication.ClassesHandle.MonHoc;

/**
 *
 * @author SON
 */
public class UIQuanLyMonHoc extends javax.swing.JFrame {
    private ArrayList<Object> alMonHoc = new ArrayList<>();
    private FileObject fileObject = new FileObject();
    /**
     * Creates new form UIQuanLyMonHoc
     */
    public UIQuanLyMonHoc() {
        initComponents();
        setInit();
    }
    
    private void setInit() {
        alMonHoc = fileObject.readObjectFrFile("MonHoc.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLMonHoc = new javax.swing.JList<>(new DefaultListModel<String>());
        jLThemMonHoc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFTenMonHoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFMaHocPhan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSPSoChuong = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAGioiThieu = new javax.swing.JTextArea();
        btnXoaMonHoc = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Môn Học");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Danh Sách Môn Học");

        jLMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLMonHoc);

        jLThemMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLThemMonHoc.setForeground(new java.awt.Color(51, 51, 255));
        jLThemMonHoc.setText("<html><u>Thêm Môn Học</u></html>");
        jLThemMonHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLThemMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLThemMonHocMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLThemMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jLThemMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Thông Tin Môn Học");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setLabelFor(jTFTenMonHoc);
        jLabel4.setText("Tên Môn Học :");

        jTFTenMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFTenMonHoc.setText("jTextField1");
        jTFTenMonHoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFTenMonHocKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setLabelFor(jTFMaHocPhan);
        jLabel5.setText("Mã Học Phần :");

        jTFMaHocPhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFMaHocPhan.setText("jTextField1");
        jTFMaHocPhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFMaHocPhanKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setLabelFor(jSPSoChuong);
        jLabel6.setText("Số Chương");

        jSPSoChuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSPSoChuongStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setLabelFor(jTAGioiThieu);
        jLabel7.setText("Giới Thiệu");

        jTAGioiThieu.setColumns(20);
        jTAGioiThieu.setLineWrap(true);
        jTAGioiThieu.setRows(5);
        jTAGioiThieu.setWrapStyleWord(true);
        jTAGioiThieu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTAGioiThieuKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTAGioiThieu);

        btnXoaMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoaMonHoc.setText("Xóa Môn Học");
        btnXoaMonHoc.setEnabled(false);
        btnXoaMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonHocActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setEnabled(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTFTenMonHoc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSPSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFMaHocPhan)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaMonHoc)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuy, btnLuu, btnXoaMonHoc});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFMaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSPSoChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy)
                    .addComponent(btnLuu))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHuy, btnLuu, btnXoaMonHoc});

        btnOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ((DefaultListModel)jLMonHoc.getModel()).removeAllElements();
        //ArrayList<Object> alMonHoc = new ArrayList<>();
        //FileObject fileObject = new FileObject();
        //alMonHoc = fileObject.readObjectFrFile("MonHoc.txt");
        clearAll();       
        if(alMonHoc != null) {
            for(Object monHoc : alMonHoc) {
                ((DefaultListModel)jLMonHoc.getModel()).addElement(((MonHoc)monHoc).getTenMonHoc());
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMonHocMouseClicked
        // TODO add your handling code here:
        clearAll();      
        btnXoaMonHoc.setEnabled(true);
        //Lay thong tin mon hoc dang duoc chon trong danh sach
        //ArrayList<Object> listMonHoc = new ArrayList<>();
        //FileObject fo = new FileObject();
        //listMonHoc = fo.readObjectFrFile("MonHoc.txt");
        setInit();
        String itemSelected = String.valueOf(jLMonHoc.getSelectedValue());
        
        for(Object monHoc : alMonHoc) {
            if(((MonHoc)monHoc).getTenMonHoc().equals(itemSelected)) {
                jTFTenMonHoc.setText(((MonHoc)monHoc).getTenMonHoc());
                jTFMaHocPhan.setText(((MonHoc)monHoc).getMaMonHoc());
                jSPSoChuong.setValue(((MonHoc)monHoc).getSoChuong());
                jTAGioiThieu.setText(((MonHoc)monHoc).getGioiThieuMonHoc());
                break;
            }
        }
    }//GEN-LAST:event_jLMonHocMouseClicked

    private void jLThemMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLThemMonHocMouseClicked
        // TODO add your handling code here:
        jLMonHoc.clearSelection();
        clearAll();
    }//GEN-LAST:event_jLThemMonHocMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        //Lay thong tin mon hoc dang duoc chon trong danh sach
        MonHoc tmpMonHoc;
        //ArrayList<Object> alMonHoc = new ArrayList<>();
        //FileObject fileObject = new FileObject();
        //alMonHoc = fileObject.readObjectFrFile("MonHoc.txt");
        String itemSelected = String.valueOf(jLMonHoc.getSelectedValue());

        if(!(itemSelected.equals("null")) || !(alMonHoc.isEmpty())) {
            for(Object monHoc : alMonHoc) {
                if(((MonHoc)monHoc).getTenMonHoc().equals(itemSelected)) {
                    tmpMonHoc = (MonHoc)monHoc;
                    tmpMonHoc.setTenMonHoc(jTFTenMonHoc.getText());
                    tmpMonHoc.setMaMonHoc(jTFMaHocPhan.getText());
                    tmpMonHoc.setSoChuong((int)jSPSoChuong.getValue());
                    tmpMonHoc.setGioiThieuMonHoc(jTAGioiThieu.getText());
                    ((DefaultListModel)jLMonHoc.getModel()).setElementAt(jTFTenMonHoc.getText(), jLMonHoc.getSelectedIndex());
                    break;
                }
            }
        }
        if(itemSelected.equals("null"))
        {
            MonHoc newMonHoc = new MonHoc(jTFTenMonHoc.getText(), jTFMaHocPhan.getText(), (int)jSPSoChuong.getValue(), jTAGioiThieu.getText());
            alMonHoc.add(newMonHoc);
            ((DefaultListModel)jLMonHoc.getModel()).addElement(jTFTenMonHoc.getText());
        }
        //Ghi thong tin ra file
        fileObject.writeObjectToFile("MonHoc.txt", alMonHoc);
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonHocActionPerformed
        // TODO add your handling code here:
        //ArrayList<Object> alMonHoc = new ArrayList<>();
        //FileObject fileObject = new FileObject();
        //alMonHoc = fileObject.readObjectFrFile("MonHoc.txt");
        String itemSelected = String.valueOf(jLMonHoc.getSelectedValue());

        if(!(itemSelected.equals("null")) || !(alMonHoc.isEmpty())) {
            for(Object monHoc : alMonHoc) {
                if(((MonHoc)monHoc).getTenMonHoc().equals(itemSelected)) {
                    ((DefaultListModel)jLMonHoc.getModel()).removeElement(((MonHoc)monHoc).getTenMonHoc());
                    clearAll();
                    alMonHoc.remove(monHoc);
                    fileObject.writeObjectToFile("MonHoc.txt", alMonHoc);
                    break;
                }
            }
        }
        btnXoaMonHoc.setEnabled(false);
    }//GEN-LAST:event_btnXoaMonHocActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        clearAll();      
        //Lay thong tin mon hoc dang duoc chon trong danh sach
        //ArrayList<Object> alMonHoc = new ArrayList<>();
        //FileObject fileObject = new FileObject();
        //alMonHoc = fileObject.readObjectFrFile("MonHoc.txt");
        String itemSelected = String.valueOf(jLMonHoc.getSelectedValue());
        
        for(Object monHoc : alMonHoc) {
            if(((MonHoc)monHoc).getTenMonHoc().equals(itemSelected)) {
                jTFTenMonHoc.setText(((MonHoc)monHoc).getTenMonHoc());
                jTFMaHocPhan.setText(((MonHoc)monHoc).getMaMonHoc());
                jSPSoChuong.setValue(((MonHoc)monHoc).getSoChuong());
                jTAGioiThieu.setText(((MonHoc)monHoc).getGioiThieuMonHoc());
                break;
            }
        }
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jTFTenMonHocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTenMonHocKeyPressed
        // TODO add your handling code here:
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_jTFTenMonHocKeyPressed

    private void jTFMaHocPhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMaHocPhanKeyPressed
        // TODO add your handling code here:
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_jTFMaHocPhanKeyPressed

    private void jTAGioiThieuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAGioiThieuKeyPressed
        // TODO add your handling code here:
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_jTAGioiThieuKeyPressed

    private void jSPSoChuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSPSoChuongStateChanged
        // TODO add your handling code here:
        String itemSelected = String.valueOf(jLMonHoc.getSelectedValue());
        for(Object obj : alMonHoc) {
            if(((MonHoc)obj).getTenMonHoc().equals(itemSelected)) {
                if(((int)jSPSoChuong.getValue()) != ((MonHoc)obj).getSoChuong()) {
                    btnLuu.setEnabled(true);
                    btnHuy.setEnabled(true);
                }
                break;
            }
        }
    }//GEN-LAST:event_jSPSoChuongStateChanged

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if(btnLuu.isEnabled()) {
            int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu lại những thay đổi không?", "Lưu thay đổi", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION) {
                btnLuuActionPerformed(evt);
                this.dispose();
            }
            else {
                this.dispose();
            }
        }
        else {
            this.dispose();
        }
    }//GEN-LAST:event_btnOKActionPerformed
    
    private void clearAll() {
        jTFTenMonHoc.setText(null);
        jTFMaHocPhan.setText(null);
        jSPSoChuong.setValue(0);
        jTAGioiThieu.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIQuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIQuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIQuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIQuanLyMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UIQuanLyMonHoc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnXoaMonHoc;
    private javax.swing.JList<String> jLMonHoc;
    private javax.swing.JLabel jLThemMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSPSoChuong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAGioiThieu;
    private javax.swing.JTextField jTFMaHocPhan;
    private javax.swing.JTextField jTFTenMonHoc;
    // End of variables declaration//GEN-END:variables
}
