/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tracnghiemapplication.UI;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import tracnghiemapplication.ClassesHandle.CauHoi;
import tracnghiemapplication.ClassesHandle.CauHoiTracNghiem;
import tracnghiemapplication.ClassesHandle.CauHoiTuLuan;
import tracnghiemapplication.ClassesHandle.FileObject;
import tracnghiemapplication.ClassesHandle.MonHoc;

/**
 *
 * @author SON
 */
public class UISoanCauHoi extends javax.swing.JFrame {
    private MonHoc monHoc;
    private ArrayList<String> dapAnDung = new ArrayList<>();
    /**
     * Creates new form UISoanCauHoi
     */
    public UISoanCauHoi() {
        initComponents();
    }
    
    public void setMonHoc(MonHoc monHoc) {
        this.monHoc = monHoc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLCauHoi = new javax.swing.JList<>(new DefaultListModel<String>());
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRBTracNghiem = new javax.swing.JRadioButton();
        jRBTuLuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADeBai = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLDapAn = new javax.swing.JList<>(new DefaultListModel<String>());
        jLBThem = new javax.swing.JLabel();
        jLBChinhSua = new javax.swing.JLabel();
        jLBXoa = new javax.swing.JLabel();
        jCheckBoxXaoTron = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBChuong = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnXoaCauHoi = new javax.swing.JButton();
        jTFDoKho = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soạn Câu Hỏi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setLabelFor(jLCauHoi);
        jLabel2.setText("Danh sách câu hỏi");

        jLCauHoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCauHoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLCauHoi);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("<html><u>Thêm Câu Hỏi</u></html>");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thông Tin Câu Hỏi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Dạng Câu Hỏi");

        jRBTracNghiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBTracNghiem.setText("Trắc nghiệm");

        jRBTuLuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRBTuLuan.setText("Tự Luận");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addComponent(jRBTracNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBTuLuan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRBTracNghiem)
                    .addComponent(jRBTuLuan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setLabelFor(jRBTracNghiem);
        jLabel5.setText("Đề bài");

        jTADeBai.setColumns(20);
        jTADeBai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTADeBai.setLineWrap(true);
        jTADeBai.setRows(5);
        jTADeBai.setWrapStyleWord(true);
        jTADeBai.setAutoscrolls(false);
        jTADeBai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTADeBaiKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTADeBai);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setLabelFor(jLDapAn);
        jLabel6.setText("Các lựa chọn đáp án");

        jLDapAn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jLDapAn);

        jLBThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBThem.setForeground(new java.awt.Color(51, 51, 255));
        jLBThem.setLabelFor(jLDapAn);
        jLBThem.setText("<html><u>Thêm</u></html>");
        jLBThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBThemMouseClicked(evt);
            }
        });

        jLBChinhSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBChinhSua.setForeground(new java.awt.Color(51, 51, 255));
        jLBChinhSua.setLabelFor(jLDapAn);
        jLBChinhSua.setText("<html><u>Chỉnh Sửa</u></html>");
        jLBChinhSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBChinhSuaMouseClicked(evt);
            }
        });

        jLBXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBXoa.setForeground(new java.awt.Color(255, 51, 51));
        jLBXoa.setLabelFor(jLDapAn);
        jLBXoa.setText("<html><u>Xóa</u></html>");
        jLBXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBXoaMouseClicked(evt);
            }
        });

        jCheckBoxXaoTron.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxXaoTron.setText("Có thể xáo trộn");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Độ khó");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setLabelFor(jCBChuong);
        jLabel8.setText("Chương");

        jCBChuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBChuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBChuongItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Câu hỏi tương đương");

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setEnabled(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setEnabled(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXoaCauHoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoaCauHoi.setText("Xóa Câu Hỏi");
        btnXoaCauHoi.setEnabled(false);
        btnXoaCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCauHoiActionPerformed(evt);
            }
        });

        jTFDoKho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFDoKho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDoKhoKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("<html><u>Click here</u></html>");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBoxXaoTron)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLBChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLBXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaCauHoi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFDoKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuy, btnLuu, btnXoaCauHoi});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCBChuong, jTFDoKho});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxXaoTron)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCBChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy)
                    .addComponent(btnXoaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCBChuong, jTFDoKho});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHuy, btnLuu, btnXoaCauHoi});

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        dapAnDung.clear();
        ((DefaultListModel)jLCauHoi.getModel()).removeAllElements();
        
        for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
            ((DefaultListModel)jLCauHoi.getModel()).addElement(cauHoi.getCauHoi());
        }
        
        for(int i = 1; i <= monHoc.getSoChuong(); i++) {
            jCBChuong.addItem("Chương " + i);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        jLCauHoi.clearSelection();
        cleanAll();
        dapAnDung.clear();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCauHoiMouseClicked
        // TODO add your handling code here:
        cleanAll();
        btnXoaCauHoi.setEnabled(true);
        String itemSelected = String.valueOf(jLCauHoi.getSelectedValue());
        
        for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
            if(cauHoi.getCauHoi().equals(itemSelected)) {

                dapAnDung.clear();
                dapAnDung.addAll(cauHoi.getDapAnDung());

                if(cauHoi instanceof CauHoiTracNghiem) {
                    jRBTracNghiem.setSelected(true);
                    jRBTuLuan.setSelected(false);
                }
                if(cauHoi instanceof CauHoiTuLuan) {
                    jRBTuLuan.setSelected(true);
                    jRBTracNghiem.setSelected(false);
                }
                jTADeBai.setText(cauHoi.getCauHoi());
                jTFDoKho.setText(String.valueOf(cauHoi.getDoKho()));
                jCBChuong.setSelectedIndex(cauHoi.getSoChuong() - 1);

                for(String da : cauHoi.getDapAn()) {
                    ((DefaultListModel)jLDapAn.getModel()).addElement(da);
                }
                break;
            }
        }
    }//GEN-LAST:event_jLCauHoiMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String itemSelected = String.valueOf(jLCauHoi.getSelectedValue());
        FileObject fileObject = new FileObject();
        ArrayList<String> tmpDapAn = new ArrayList<>();
        if(!(itemSelected.equals("null"))) {
            if(jRBTracNghiem.isSelected() || jRBTuLuan.isSelected()) {
                for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
                    if(cauHoi.getCauHoi().equals(itemSelected)) {
                        String tmpCauHoi = jTADeBai.getText().replaceAll("\n", " ");
                        cauHoi.setCauHoi(tmpCauHoi);
                        cauHoi.setDoKho(Integer.parseInt(jTFDoKho.getText()));
                        cauHoi.setSoChuong(jCBChuong.getSelectedIndex() + 1);
                        for(int i = 0; i < ((DefaultListModel)jLDapAn.getModel()).getSize(); i++) {
                            tmpDapAn.add((String) ((DefaultListModel)jLDapAn.getModel()).getElementAt(i));
                        }
                        cauHoi.setDapAn(tmpDapAn);
                        cauHoi.setDapAnDung(dapAnDung);
                        break;
                    }
                }
            }
        }
        if(itemSelected.equals("null")) {
            if(jRBTracNghiem.isSelected() && !(jTADeBai.getText().isEmpty()) && !(jTFDoKho.getText().isEmpty())) {
                CauHoiTracNghiem tmpTracNghiem = new CauHoiTracNghiem(jTADeBai.getText(), jCBChuong.getSelectedIndex() + 1, Integer.parseInt(jTFDoKho.getText()));
                for(int i = 0; i < ((DefaultListModel)jLDapAn.getModel()).getSize(); i++) {
                    tmpDapAn.add((String) ((DefaultListModel)jLDapAn.getModel()).getElementAt(i));
                }
                tmpTracNghiem.setDapAn(tmpDapAn);
                tmpTracNghiem.setDapAnDung(dapAnDung);
                monHoc.themCauHoi(tmpTracNghiem);
                ((DefaultListModel)jLCauHoi.getModel()).addElement(jTADeBai.getText()); 
            }
            else if(jRBTuLuan.isSelected() && !(jTADeBai.getText().isEmpty()) && !(jTFDoKho.getText().isEmpty())) {
                CauHoiTuLuan tmpTuLuan = new CauHoiTuLuan(jTADeBai.getText(), jCBChuong.getSelectedIndex() + 1, Integer.parseInt(jTFDoKho.getText()));
                for(int i = 0; i < ((DefaultListModel)jLDapAn.getModel()).getSize(); i++) {
                    tmpDapAn.add((String) ((DefaultListModel)jLDapAn.getModel()).getElementAt(i));
                }
                tmpTuLuan.setDapAn(tmpDapAn);
                tmpTuLuan.setDapAnDung(dapAnDung);
                monHoc.themCauHoi(tmpTuLuan);
                ((DefaultListModel)jLCauHoi.getModel()).addElement(jTADeBai.getText()); 
            }
            else {
                JOptionPane.showMessageDialog(null, "Bạn điền chưa đủ thông tin! Vui lòng kiểm tra lại", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        fileObject.updateObjectInFile("MonHoc.txt", monHoc);
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void jLBThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBThemMouseClicked
        // TODO add your handling code here:
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
        UINhapDanAn nhapDapAn = new UINhapDanAn();
        nhapDapAn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nhapDapAn.setVisible(true);
        nhapDapAn.getJButton().addActionListener((ActionEvent e) -> {
            ((DefaultListModel)this.getJList().getModel()).addElement(nhapDapAn.getJTextField().getText());
            if(nhapDapAn.getJCheckBox().isSelected()) {
                dapAnDung.add(nhapDapAn.getJTextField().getText());
            }
            nhapDapAn.dispose();
        });
    }//GEN-LAST:event_jLBThemMouseClicked

    private void jTADeBaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTADeBaiKeyPressed
        // TODO add your handling code here:
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_jTADeBaiKeyPressed

    private void jTFDoKhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDoKhoKeyPressed
        // TODO add your handling code here:
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }//GEN-LAST:event_jTFDoKhoKeyPressed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        cleanAll();
        btnXoaCauHoi.setEnabled(true);
        String itemSelected = String.valueOf(jLCauHoi.getSelectedValue());
        
        for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
            if(cauHoi.getCauHoi().equals(itemSelected)) {
                if(cauHoi instanceof CauHoiTracNghiem) {
                    jRBTracNghiem.setSelected(true);
                    jRBTuLuan.setSelected(false);
                }
                if(cauHoi instanceof CauHoiTuLuan) {
                    jRBTuLuan.setSelected(true);
                    jRBTracNghiem.setSelected(false);
                }
                jTADeBai.setText(cauHoi.getCauHoi());
                jTFDoKho.setText(String.valueOf(cauHoi.getDoKho()));
                jCBChuong.setSelectedIndex(cauHoi.getSoChuong() - 1);

                for(String da : cauHoi.getDapAn()) {
                    ((DefaultListModel)jLDapAn.getModel()).addElement(da);
                }
                break;
            }
        }
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCauHoiActionPerformed
        // TODO add your handling code here:
        String itemSelected = String.valueOf(jLCauHoi.getSelectedValue());
        FileObject fileObject = new FileObject();
        if(!(itemSelected.equals("null"))) {
            for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
                if(cauHoi.getCauHoi().equals(itemSelected)) {
                    monHoc.xoaCauHoi(cauHoi);
                    fileObject.updateObjectInFile("MonHoc.txt", monHoc);
                    ((DefaultListModel)jLCauHoi.getModel()).removeElement(itemSelected);
                    break;
                }
            }
        }
        btnXoaCauHoi.setEnabled(false);
        cleanAll();
        dapAnDung.clear();
    }//GEN-LAST:event_btnXoaCauHoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(btnLuu.isEnabled()) {
            int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu lại những thay đổi không?", "Lưu thay đổi", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION) {
                btnLuuActionPerformed(evt);
                this.dispose();
            }
            else {
                this.dispose();
            }
        }
        else {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCBChuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBChuongItemStateChanged
        // TODO add your handling code here:
        String itemSelected = String.valueOf(jLCauHoi.getSelectedValue());
        String itemChuong = String.valueOf(jCBChuong.getSelectedItem());
        for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
            if(cauHoi.getCauHoi().equals(itemSelected)) {
                if(!(itemChuong.equals("Chương " + cauHoi.getSoChuong()))) {
                    btnLuu.setEnabled(true);
                    btnHuy.setEnabled(true);
                }
                break;
            }
        }
    }//GEN-LAST:event_jCBChuongItemStateChanged

    private void jLBChinhSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBChinhSuaMouseClicked
        // TODO add your handling code here:
        boolean isTrue = false;
        if(!(jLDapAn.getSelectedValue().isEmpty())) {
            btnLuu.setEnabled(true);
            btnHuy.setEnabled(true);
            String itemSelected = jLDapAn.getSelectedValue();
            for(String dad : dapAnDung) {
                if(dad.equals(itemSelected)) {
                    isTrue = true;
                    dapAnDung.remove(dad);
                    break;
                }
            }
            UINhapDanAn nhapDapAn = new UINhapDanAn();
            nhapDapAn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            //nhapDapAn.suaGiaTri(itemSelected);
            nhapDapAn.getJTextField().setText(itemSelected);
            nhapDapAn.getJCheckBox().setSelected(isTrue);
            nhapDapAn.setVisible(true);
            nhapDapAn.getJButton().addActionListener((ActionEvent e) -> {
                ((DefaultListModel)this.getJList().getModel()).setElementAt(nhapDapAn.getJTextField().getText(), this.getJList().getSelectedIndex());
                if(nhapDapAn.getJCheckBox().isSelected()) {
                    dapAnDung.add(nhapDapAn.getJTextField().getText());
                }
                nhapDapAn.dispose();
            });
        }
    }//GEN-LAST:event_jLBChinhSuaMouseClicked

    private void jLBXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBXoaMouseClicked
        // TODO add your handling code here:
        if(!(jLDapAn.getSelectedValue().isEmpty())) {
            btnLuu.setEnabled(true);
            btnHuy.setEnabled(true);
            String itemSelected = jLDapAn.getSelectedValue();
            for(String dad : dapAnDung) {
                if(dad.equals(itemSelected)) {
                    dapAnDung.remove(dad);
                    break;
                }
            }
            ((DefaultListModel)jLDapAn.getModel()).removeElement(jLDapAn.getSelectedValue());
        }
    }//GEN-LAST:event_jLBXoaMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        String cauHoi = jTADeBai.getText();
        ArrayList<CauHoi> cauHoiTuongDuong = new ArrayList<>();
        if(!(cauHoi.isEmpty())) {
            ArrayList<String> wordSource = new ArrayList<>(Arrays.asList(cauHoi.split(" ")));
            wordSource.replaceAll((String word) -> word.toUpperCase());
            ArrayList<String> wordDestination;
            for(CauHoi ch : monHoc.getDSCauHoi()) {
                int count = 0;
                wordDestination = new ArrayList<>(Arrays.asList(ch.getCauHoi().split(" ")));
                wordDestination.replaceAll((String word) -> word.toUpperCase());
                for(String word : wordSource) {
                    if(wordDestination.contains(word)) {
                        count++;
                    }
                }
                if(((double)count/wordDestination.size()) > 0.7) {
                    cauHoiTuongDuong.add(ch);
                }
            }
            UICauHoiTuongDuong cauHoiTD = new UICauHoiTuongDuong();
            cauHoiTD.setCauHoiTuongDuong(cauHoiTuongDuong);
            cauHoiTD.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            cauHoiTD.setVisible(true);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void cleanAll() {
        jRBTracNghiem.setSelected(false);
        jRBTuLuan.setSelected(false);
        jTADeBai.setText(null);
        ((DefaultListModel)jLDapAn.getModel()).removeAllElements();
        jCheckBoxXaoTron.setSelected(false);
        jTFDoKho.setText(null);
    }
    
    public JList getJList() {
        return jLDapAn;
    }
    
    public JList getJListCauHoi() {
        return jLCauHoi;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UISoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UISoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UISoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UISoanCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UISoanCauHoi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnXoaCauHoi;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBChuong;
    private javax.swing.JCheckBox jCheckBoxXaoTron;
    private javax.swing.JLabel jLBChinhSua;
    private javax.swing.JLabel jLBThem;
    private javax.swing.JLabel jLBXoa;
    private javax.swing.JList<String> jLCauHoi;
    private javax.swing.JList<String> jLDapAn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBTracNghiem;
    private javax.swing.JRadioButton jRBTuLuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTADeBai;
    private javax.swing.JTextField jTFDoKho;
    // End of variables declaration//GEN-END:variables
}
