/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tracnghiemapplication.UI;

import com.itextpdf.text.Paragraph;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import tracnghiemapplication.ClassesHandle.CauHoi;
import tracnghiemapplication.ClassesHandle.CauHoiTracNghiem;
import tracnghiemapplication.ClassesHandle.CauHoiTuLuan;
import tracnghiemapplication.ClassesHandle.DeThi;
import tracnghiemapplication.ClassesHandle.FileObject;
import tracnghiemapplication.ClassesHandle.MonHoc;

/**
 *
 * @author SON
 */
public class UITuTaoDeThi extends javax.swing.JFrame {
    private MonHoc monHoc;
    private DeThi tmpDeThi;
    private static int number = 0;
    private boolean trangThaiLuu = false;
    public String tenDeThi;
    /**
     * Creates new form CustomQuestion
     */
    public UITuTaoDeThi() {
        initComponents();
    }
    
    public void setMonHoc(MonHoc monHoc) {
        this.monHoc = monHoc;
    }
    
    public void setTrangThaiLuu(boolean trangThaiLuu) {
        this.trangThaiLuu = trangThaiLuu;
    }
    
    public void setTenDeThi(String tenDeThi) {
        this.tenDeThi = tenDeThi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLDSCauHoi = new javax.swing.JList<>(new DefaultListModel<String>());
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRBTatCa = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRBTracNghiem = new javax.swing.JRadioButton();
        jRBTuLuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLDSCauHoiTrongDe = new javax.swing.JList<>(new DefaultListModel<String>());
        jLXemTruoc = new javax.swing.JLabel();
        jLThayTheCauHoi = new javax.swing.JLabel();
        jLXoaCauHoi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFThoiGian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFNamHoc = new javax.swing.JTextField();
        jRBKyI = new javax.swing.JRadioButton();
        jRBKyII = new javax.swing.JRadioButton();
        jRBKyHe = new javax.swing.JRadioButton();
        jLXuatFile = new javax.swing.JLabel();
        btnLuuDe = new javax.swing.JButton();
        btnXoaDe = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTFDiem = new javax.swing.JTextField();
        btnThemCauVaoDe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAChiTietCauHoi = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAXemTruoc = new javax.swing.JTextArea();
        jLBTenDe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setLabelFor(jLDSCauHoi);
        jLabel2.setText("Danh sách câu hỏi");

        jLDSCauHoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDSCauHoi.setName("list_cauhoi"); // NOI18N
        jLDSCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLDSCauHoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLDSCauHoi);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Chi tiết câu hỏi");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Chọn ngẫu nhiên");
        jButton1.setName("btn_randomquestion"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRBTatCa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBTatCa.setText("Tất cả");
        jRBTatCa.setName("rb_tatca"); // NOI18N
        jRBTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBTatCaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Dạng câu hỏi");

        jRBTracNghiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBTracNghiem.setText("Trắc nghiệm");
        jRBTracNghiem.setName("rb_tracnghiem"); // NOI18N
        jRBTracNghiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBTracNghiemMouseClicked(evt);
            }
        });

        jRBTuLuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBTuLuan.setText("Tự luận");
        jRBTuLuan.setName("rb_tuluan"); // NOI18N
        jRBTuLuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBTuLuanMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setLabelFor(jLDSCauHoiTrongDe);
        jLabel5.setText("Danh sách câu trong đề");

        jLDSCauHoiTrongDe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDSCauHoiTrongDe.setName("list_cauhoitrongde"); // NOI18N
        jScrollPane3.setViewportView(jLDSCauHoiTrongDe);

        jLXemTruoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLXemTruoc.setText("Xem trước");
        jLXemTruoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLXemTruoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLXemTruocMouseClicked(evt);
            }
        });

        jLThayTheCauHoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLThayTheCauHoi.setForeground(new java.awt.Color(0, 102, 255));
        jLThayTheCauHoi.setLabelFor(jLDSCauHoiTrongDe);
        jLThayTheCauHoi.setText("<html><u>Thay thế bằng câu hỏi khác</u></html>");
        jLThayTheCauHoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLThayTheCauHoi.setName("click_thaythe"); // NOI18N
        jLThayTheCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLThayTheCauHoiMouseClicked(evt);
            }
        });

        jLXoaCauHoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLXoaCauHoi.setForeground(new java.awt.Color(255, 0, 0));
        jLXoaCauHoi.setLabelFor(jLDSCauHoiTrongDe);
        jLXoaCauHoi.setText("<html><u>Xóa câu hỏi ra khỏi đề thi</u></html>");
        jLXoaCauHoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLXoaCauHoi.setName("click_xoacauhoi"); // NOI18N
        jLXoaCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLXoaCauHoiMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Thông tin đề thi");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setLabelFor(jTFThoiGian);
        jLabel10.setText("Thời gian");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setLabelFor(jTFNamHoc);
        jLabel11.setText("Năm học");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Kỳ");

        jTFThoiGian.setName("textfile_thoigian"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("phút");

        jTFNamHoc.setName("textfield_namhoc"); // NOI18N

        jRBKyI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRBKyI.setText("1");
        jRBKyI.setName("rb_ky1"); // NOI18N

        jRBKyII.setText("2");
        jRBKyII.setName("rb_ky2"); // NOI18N

        jRBKyHe.setText("kỳ hè");
        jRBKyHe.setName("rb_kyhe"); // NOI18N

        jLXuatFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLXuatFile.setForeground(new java.awt.Color(0, 51, 255));
        jLXuatFile.setText("<html><u>Xuất file</u></html>");
        jLXuatFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLXuatFile.setName("click_xuatfile"); // NOI18N
        jLXuatFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLXuatFileMouseClicked(evt);
            }
        });

        btnLuuDe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLuuDe.setText("Lưu đề thi");
        btnLuuDe.setName("btn_luudethi"); // NOI18N
        btnLuuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDeActionPerformed(evt);
            }
        });

        btnXoaDe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoaDe.setText("Xóa đề thi");
        btnXoaDe.setName("btn_xoadethi"); // NOI18N
        btnXoaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setLabelFor(jTFDiem);
        jLabel15.setText("Điểm cho câu hỏi");

        jTFDiem.setName("textField_diemcau"); // NOI18N

        btnThemCauVaoDe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThemCauVaoDe.setText("Thêm câu hỏi vào đề");
        btnThemCauVaoDe.setName("btn_themcauvaode"); // NOI18N
        btnThemCauVaoDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCauVaoDeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lựa chọn câu hỏi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jTAChiTietCauHoi.setColumns(20);
        jTAChiTietCauHoi.setRows(5);
        jScrollPane2.setViewportView(jTAChiTietCauHoi);

        jTAXemTruoc.setColumns(20);
        jTAXemTruoc.setRows(5);
        jScrollPane5.setViewportView(jTAXemTruoc);

        jLBTenDe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFNamHoc)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRBKyI)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRBKyII)
                                                .addGap(11, 11, 11)
                                                .addComponent(jRBKyHe)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLThayTheCauHoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLXoaCauHoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBTatCa)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBTracNghiem)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBTuLuan))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTFThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(136, 136, 136)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                                .addComponent(btnThemCauVaoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLXemTruoc)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLBTenDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(btnThemCauVaoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBTatCa)
                    .addComponent(jRBTracNghiem)
                    .addComponent(jRBTuLuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLXemTruoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLThayTheCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLXoaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTFThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTFNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jRBKyI)
                    .addComponent(jRBKyII)
                    .addComponent(jRBKyHe)
                    .addComponent(jLXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBTenDe))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ((DefaultListModel)jLDSCauHoi.getModel()).removeAllElements();
        jRBTatCa.setSelected(true);
        for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
            ((DefaultListModel)jLDSCauHoi.getModel()).addElement(cauHoi.getCauHoi());
        }
        
        if(trangThaiLuu) {
            tmpDeThi = new DeThi();
            UINhapTenDeThi nhapTenDeThi = new UINhapTenDeThi();
            nhapTenDeThi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            nhapTenDeThi.setVisible(true);
            nhapTenDeThi.getJButtonOK().addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    tenDeThi = nhapTenDeThi.jTFTenDeThi.getText();
                    nhapTenDeThi.dispose();
                }
            });
        }
        else {
            for(DeThi deThi : monHoc.getDeThi()) {
                if(deThi.getTenDeThi().equals(tenDeThi)) {
                    tmpDeThi = deThi;
                    break;
                }
            }
            
            number = tmpDeThi.getDSCauHoi().size();
            
            for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
                ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).addElement("Câu " + (tmpDeThi.getDSCauHoi().indexOf(cauHoi) + 1) + ": " + cauHoi.getCauHoi());
            }
            jTFNamHoc.setText(tmpDeThi.getNamHoc());
            jTFThoiGian.setText(tmpDeThi.getThoiGian());
            if(tmpDeThi.getLoaiDeThi().equals("kỳ 1")) {
                jRBKyI.setSelected(true);
            }
            else if(tmpDeThi.getLoaiDeThi().equals("kỳ 2")) {
                jRBKyII.setSelected(true);
            }
            else {
                jRBKyHe.setSelected(true);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLDSCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLDSCauHoiMouseClicked
        // TODO add your handling code here:
        jTAChiTietCauHoi.setText(null);
        jTFDiem.setText(null);
        String itemSelected = String.valueOf(jLDSCauHoi.getSelectedValue());
        for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
            if(cauHoi.getCauHoi().equals(itemSelected)) {
                cauHoi.inCauHoi(jTAChiTietCauHoi);
                jTAChiTietCauHoi.append("-----------------------------------------------------------\n");
                jTAChiTietCauHoi.append("Thông tin chi tiết :\n");
                jTAChiTietCauHoi.append("Đáp án: ");
                for(String da : cauHoi.getDapAnDung()) {
                    jTAChiTietCauHoi.append(da + "\t");
                }
                jTAChiTietCauHoi.append("\nĐộ khó: " + cauHoi.getDoKho() + "\n");
                jTAChiTietCauHoi.append("Chương: Chương " + cauHoi.getSoChuong() + "\n");
                break;
            }
        }
    }//GEN-LAST:event_jLDSCauHoiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTAChiTietCauHoi.setText(null);
        jTFDiem.setText(null);
        Random rd = new Random();
        int index = rd.nextInt(monHoc.getDSCauHoi().size()) + 0;
        jLDSCauHoi.setSelectedIndex(index);
        String itemSelected = String.valueOf(jLDSCauHoi.getSelectedValue());
        for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
            if(cauHoi.getCauHoi().equals(itemSelected)) {
                cauHoi.inCauHoi(jTAChiTietCauHoi);
                jTAChiTietCauHoi.append("-----------------------------------------------------------\n");
                jTAChiTietCauHoi.append("Thông tin chi tiết :\n");
                jTAChiTietCauHoi.append("Đáp án: ");
                for(String da : cauHoi.getDapAnDung()) {
                    jTAChiTietCauHoi.append(da + "\t");
                }
                jTAChiTietCauHoi.append("\nĐộ khó: " + cauHoi.getDoKho() + "\n");
                jTAChiTietCauHoi.append("Chương: Chương " + cauHoi.getSoChuong() + "\n");
                break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemCauVaoDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCauVaoDeActionPerformed
        // TODO add your handling code here:
        number += 1;
        if(!(jTFDiem.getText().isEmpty())) {
            String itemSelected = String.valueOf(jLDSCauHoi.getSelectedValue());
            for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
                if(cauHoi.getCauHoi().equals(itemSelected)) {
                    JOptionPane.showMessageDialog(null, "Câu hỏi đã có trong đề thi", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            for(CauHoi cauHoi : monHoc.getDSCauHoi()) {
                if(cauHoi.getCauHoi().equals(itemSelected)) {
                    cauHoi.setDiemDatDuoc(Double.parseDouble(jTFDiem.getText()));
                    tmpDeThi.themCauHoi(cauHoi);
                    break;
                }
            }
            ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).addElement("Câu " + number + ": " + itemSelected);
        }
    }//GEN-LAST:event_btnThemCauVaoDeActionPerformed

    private void jRBTracNghiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBTracNghiemMouseClicked
        // TODO add your handling code here:
        jRBTuLuan.setSelected(false);
        jRBTatCa.setSelected(false);
        ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).removeAllElements();
        for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
            if(cauHoi instanceof CauHoiTracNghiem) {
                ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).addElement("Câu " + (tmpDeThi.getDSCauHoi().indexOf(cauHoi) + 1) + ": " + cauHoi.getCauHoi());                
            }
        }
    }//GEN-LAST:event_jRBTracNghiemMouseClicked

    private void jRBTuLuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBTuLuanMouseClicked
        // TODO add your handling code here:
        jRBTracNghiem.setSelected(false);
        jRBTatCa.setSelected(false);
        ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).removeAllElements();
        for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
            if(cauHoi instanceof CauHoiTuLuan) {
                ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).addElement("Câu " + (tmpDeThi.getDSCauHoi().indexOf(cauHoi) + 1) + ": " + cauHoi.getCauHoi());                
            }
        }
    }//GEN-LAST:event_jRBTuLuanMouseClicked

    private void jRBTatCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBTatCaMouseClicked
        // TODO add your handling code here:
        jRBTracNghiem.setSelected(false);
        jRBTuLuan.setSelected(false);
        ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).removeAllElements();
        for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
            ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).addElement("Câu " + (tmpDeThi.getDSCauHoi().indexOf(cauHoi) + 1) + ": " + cauHoi.getCauHoi());                
        }
    }//GEN-LAST:event_jRBTatCaMouseClicked

    private void jLXemTruocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLXemTruocMouseClicked
        // TODO add your handling code here:
        jTAXemTruoc.setText(null);
        double tongDiem = 0;
        jTAXemTruoc.append("BÀI THI MÔN " + monHoc.getTenMonHoc().toUpperCase() + "\n");
        jTAXemTruoc.append((jRBKyI.isSelected() ? "Kỳ 1" : jRBKyII.isSelected() ? "Kỳ 2" : "Kỳ hè") + " - " + jTFNamHoc.getText() + "\n");
        jTAXemTruoc.append("Thời gian : " + jTFThoiGian.getText() + " phút" + "\n");
        jTAXemTruoc.append("\n\n");
        for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
            tongDiem += cauHoi.getDiemDatDuoc();
            jTAXemTruoc.append("Câu " + String.valueOf(tmpDeThi.getDSCauHoi().indexOf(cauHoi) + 1) + " (" + cauHoi.getDiemDatDuoc() + " điểm)\n");
            cauHoi.inCauHoi(jTAXemTruoc);
            jTAXemTruoc.append("\n");
        }
        jTAXemTruoc.append("\nTổng điểm: " + tongDiem + "\n");
    }//GEN-LAST:event_jLXemTruocMouseClicked

    private void jLThayTheCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLThayTheCauHoiMouseClicked
        // TODO add your handling code here:
        UIChonCauHoiThayThe chonCauHoiThayThe = new UIChonCauHoiThayThe();
        chonCauHoiThayThe.setMonHoc(monHoc);
        chonCauHoiThayThe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        chonCauHoiThayThe.setVisible(true);
        chonCauHoiThayThe.getJButton().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String itemSelected = (String) chonCauHoiThayThe.getJLDSCauHoi().getSelectedValue();
                for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
                    if(cauHoi.getCauHoi().equals(itemSelected)) {
                        JOptionPane.showMessageDialog(null, "Câu hỏi này đã có trong đề thi", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                int index = jLDSCauHoiTrongDe.getSelectedIndex();
                ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).removeElementAt(index);
                ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).add(index, itemSelected);
                chonCauHoiThayThe.dispose();
            }
        });
    }//GEN-LAST:event_jLThayTheCauHoiMouseClicked

    private void jLXoaCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLXoaCauHoiMouseClicked
        // TODO add your handling code here:
        String itemSelected = jLDSCauHoiTrongDe.getSelectedValue();
        String subItemSelected = itemSelected.substring(7, itemSelected.length());
        for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
            if(cauHoi.getCauHoi().equals(subItemSelected)) {
                ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).removeElementAt(tmpDeThi.getDSCauHoi().indexOf(cauHoi));
                tmpDeThi.getDSCauHoi().remove(cauHoi);
                break;
            }
        }
    }//GEN-LAST:event_jLXoaCauHoiMouseClicked

    private void btnLuuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDeActionPerformed
        // TODO add your handling code here:
        if(!(jTFNamHoc.getText().isEmpty()) && !(jTFThoiGian.getText().isEmpty()) && ((DefaultListModel)jLDSCauHoiTrongDe.getModel()).size() > 0) {
            FileObject fileObject = new FileObject();
            tmpDeThi.setTenDeThi(tenDeThi);
            tmpDeThi.setLoaiDeThi(jRBKyI.isSelected() ? "kỳ 1" : jRBKyII.isSelected() ? "kỳ 2" : "kỳ hè");
            tmpDeThi.setThoiGian(jTFThoiGian.getText());
            tmpDeThi.setNamHoc(jTFNamHoc.getText());
            if(trangThaiLuu) {
                monHoc.themDeThi(tmpDeThi);
            }
            fileObject.updateObjectInFile("MonHoc.txt", monHoc);
            trangThaiLuu = false;
            UIQuanLyDeThi.isFocus = true;
        }
    }//GEN-LAST:event_btnLuuDeActionPerformed

    private void btnXoaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDeActionPerformed
        // TODO add your handling code here:
        if(!trangThaiLuu) {
            FileObject fileObject = new FileObject();
            monHoc.xoaDeThi(tmpDeThi);
            fileObject.updateObjectInFile("MonHoc.txt", monHoc);
            UIQuanLyDeThi.isFocus = true;
            this.dispose();
        }
    }//GEN-LAST:event_btnXoaDeActionPerformed

    private void jLXuatFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLXuatFileMouseClicked
        FileOutputStream fos = null;
        String[] dsDapAn = {"A", "B", "C", "D", "E", "F", "G", "H"};
        try {
            jTAXemTruoc.setText(null);
            jLXemTruocMouseClicked(evt);
            ArrayList<String> contentPage = new ArrayList<>();
            contentPage.addAll(Arrays.asList(jTAXemTruoc.getText().split("\\n")));
            //Khoi tao doi tuong sinh file word
            XWPFDocument document = new XWPFDocument();
            //Tao tieu de bai viet
            XWPFParagraph titleGraph = document.createParagraph();
            titleGraph.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun titleRun = titleGraph.createRun();
            titleRun.setFontFamily("Times New Roman");
            titleRun.setBold(true);
            titleRun.setFontSize(18);
            titleRun.setText("BÀI THI MÔN " + monHoc.getTenMonHoc().toUpperCase());
            
            XWPFParagraph subTitleGraph = document.createParagraph();
            subTitleGraph.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun subTitleRun = subTitleGraph.createRun();
            subTitleRun.setFontFamily("Times New Roman");
            subTitleRun.setFontSize(14);
            subTitleRun.setItalic(true);
            subTitleRun.setText((jRBKyI.isSelected() ? "Kỳ 1" : jRBKyII.isSelected() ? "Kỳ 2" : "Kỳ hè") + " - " + jTFNamHoc.getText());
            subTitleRun.addBreak();
            subTitleRun.setText("Thời gian : " + jTFThoiGian.getText() + " phút");
            
            //Tao khoang cach giua tieu de va noi dung
            XWPFParagraph paraBreak1 = document.createParagraph();
            XWPFRun runBreak1 = paraBreak1.createRun();
            runBreak1.addBreak();
            
            //Noi dung
            XWPFParagraph contentGraph = document.createParagraph();
            contentGraph.setAlignment(ParagraphAlignment.LEFT);
            
            XWPFRun paraContent = contentGraph.createRun();
            paraContent.setFontFamily("Times New Roman");
            paraContent.setFontSize(14);
            
            for(CauHoi cauHoi : tmpDeThi.getDSCauHoi()) {
                paraContent.setText("Câu " + String.valueOf(tmpDeThi.getDSCauHoi().indexOf(cauHoi) + 1) + " (" + cauHoi.getDiemDatDuoc() + " điểm)");
                paraContent.addBreak();
                paraContent.setText(cauHoi.getCauHoi());
                paraContent.addBreak();
                for(String dapAn : cauHoi.getDapAn()) {
                    paraContent.setText(dsDapAn[cauHoi.getDapAn().indexOf(dapAn)] + ". " + dapAn);
                    paraContent.addTab();
                    paraContent.addTab();
                }
                paraContent.addBreak();
                paraContent.addBreak();
            }
            
            File fout = new File("exportToFile/" + tenDeThi + ".docx");
            if(fout.exists()) {
                fos = new FileOutputStream(fout, false);
            }
            else {
                fout.getParentFile().mkdirs();
                fout.createNewFile();
                fos = new FileOutputStream(fout);
            }
            
            //out = new FileOutputStream(tenDeThi + ".docx");
            document.write(fos);
            fos.close();
            document.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UITuTaoDeThi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UITuTaoDeThi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLXuatFileMouseClicked

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UITuTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UITuTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UITuTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UITuTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UITuTaoDeThi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuDe;
    private javax.swing.JButton btnThemCauVaoDe;
    private javax.swing.JButton btnXoaDe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBTenDe;
    private javax.swing.JList<String> jLDSCauHoi;
    private javax.swing.JList<String> jLDSCauHoiTrongDe;
    private javax.swing.JLabel jLThayTheCauHoi;
    private javax.swing.JLabel jLXemTruoc;
    private javax.swing.JLabel jLXoaCauHoi;
    private javax.swing.JLabel jLXuatFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBKyHe;
    private javax.swing.JRadioButton jRBKyI;
    private javax.swing.JRadioButton jRBKyII;
    private javax.swing.JRadioButton jRBTatCa;
    private javax.swing.JRadioButton jRBTracNghiem;
    private javax.swing.JRadioButton jRBTuLuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTAChiTietCauHoi;
    private javax.swing.JTextArea jTAXemTruoc;
    private javax.swing.JTextField jTFDiem;
    private javax.swing.JTextField jTFNamHoc;
    private javax.swing.JTextField jTFThoiGian;
    // End of variables declaration//GEN-END:variables
}
